name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '18 8,16 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://elektrodistribucija.rs/aktuelnosti/saopstenja/saopstenja > saopstenja.html
        curl https://elektrodistribucija.rs/Dan_0_Iskljucenja.htm > planirana-iskljucenja-beograd.html
        curl https://elektrodistribucija.rs/NoviSad_Dan_0_Iskljucenja.htm > planirana-iskljucenja-novi-sad.html
        curl https://elektrodistribucija.rs/Kraljevo_Dan_0_Iskljucenja.htm > planirana-iskljucenja-kraljevo.html
        curl https://elektrodistribucija.rs/Kragujevac_Dan_0_Iskljucenja.htm > planirana-iskljucenja-kragujevac.html
        curl https://elektrodistribucija.rs/Nis_Dan_0_Iskljucenja.htm > planirana-iskljucenja-nis.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
